/**
 * @file        rexglue/commands/codegen_command.cpp
 * @brief       Code generation command implementation
 *
 * @copyright   Copyright (c) 2026 Tom Clay
 * @license     BSD 3-Clause License
 */

#include "codegen_command.h"
#include "../ui/progress.h"
#include "../ui/ui.h"
#include "project_scan.h"
#include "template_utils.h"

#include <filesystem>
#include <memory>
#include <span>
#include <string_view>
#include <unordered_set>
#include <vector>

#include <CLI/CLI.hpp>
#include <fmt/format.h>

#include <rex/codegen/manifest.h>
#include <rex/codegen/project_recompiler.h>
#include <rex/logging.h>
#include <rex/version.h>

namespace rexglue::cli {

namespace {

namespace fs = std::filesystem;

void EmitManualReview(std::span<const SourceWarning> warnings, std::string_view header) {
  if (warnings.empty())
    return;
  std::vector<ui::ManualReviewRow> rows;
  rows.reserve(warnings.size());
  for (const auto& w : warnings) {
    rows.push_back(
        {fmt::format("{}:{}", w.file.generic_string(), w.line_number), w.detail, w.hint});
  }
  ui::ManualReviewList(std::string(header), rows);
}

void ReportStaleIncludes(const fs::path& manifest_path,
                         const rex::codegen::ProjectRecompiler& recompiler) {
  std::unordered_set<std::string> written(recompiler.writtenFiles().begin(),
                                          recompiler.writtenFiles().end());
  std::unordered_set<std::string> removed;
  for (const auto& f : recompiler.deletedFiles()) {
    if (!written.contains(f)) {
      removed.insert(f);
    }
  }
  if (removed.empty())
    return;

  auto matches = ScanStaleIncludes(manifest_path.parent_path() / "src", removed);
  EmitManualReview(matches,
                   fmt::format("{} source file(s) reference headers no longer emitted by codegen:",
                               matches.size()));
}

Result<void> RecompileProject(const fs::path& manifest_path, const CliContext& ctx,
                              const std::vector<std::string>& targets, bool ignore_stamp) {
  auto manifest = rex::codegen::ManifestConfig::Load(manifest_path);
  if (!manifest) {
    return Err<void>(rex::ErrorCategory::Config, "Failed to load manifest");
  }
  std::string title = fmt::format("Recompiling {}", manifest->projectName);
  rex::codegen::ProjectRecompiler recompiler(std::move(*manifest));
  ui::ProgressView progress(title);
  rex::codegen::ProjectRecompilerOptions opts{
      .targets = targets,
      .force = ctx.generate_despite_errors,
      .reporter = &progress,
      .ignoreStamp = ignore_stamp,
      .sdkVersion = REXGLUE_VERSION_FLOOR "-" REXGLUE_VERSION_CHANNEL,
  };
  auto result = recompiler.Run(opts);
  if (!result)
    return result;

  ReportStaleIncludes(manifest_path, recompiler);
  REXLOG_INFO("Codegen summary: {} written, {} unchanged, {} deleted, {} module(s) up to date",
              recompiler.writtenFiles().size(), recompiler.unchangedFiles().size(),
              recompiler.deletedFiles().size(), recompiler.skippedModules().size());
  return rex::Ok();
}

struct ManifestSummary {
  std::string project_name;
  std::string sdk_version;
  std::string entrypoint_out_dir;
  std::size_t module_count = 0;
};

rex::Result<ManifestSummary> LoadManifestSummary(const fs::path& manifest_path) {
  auto manifest = rex::codegen::ManifestConfig::Load(manifest_path);
  if (!manifest) {
    return Err<ManifestSummary>(rex::ErrorCategory::Config, "Failed to load manifest");
  }
  return rex::Ok(ManifestSummary{
      .project_name = manifest->projectName,
      .sdk_version = manifest->sdkVersion.value_or(""),
      .entrypoint_out_dir = manifest->entrypoint.recompiler.outDirectoryPath,
      .module_count = manifest->modules.size(),
  });
}

void EmitProjectHeader(const fs::path& manifest_path, const ManifestSummary& summary) {
  std::vector<ui::KeyValueRow> rows;
  rows.push_back({"Manifest", manifest_path.generic_string()});
  if (!summary.project_name.empty()) {
    rows.push_back({"Project", summary.project_name});
  }
  if (summary.module_count > 0) {
    rows.push_back({"Modules", fmt::format("{} DLL{}", summary.module_count,
                                           summary.module_count == 1 ? "" : "s")});
  }
  if (!summary.sdk_version.empty()) {
    rows.push_back({"SDK", fmt::format("{} (project last generated by {})", REXGLUE_VERSION_STRING,
                                       summary.sdk_version)});
  } else {
    rows.push_back({"SDK", REXGLUE_VERSION_STRING});
  }
  ui::KeyValueBlock("", rows);
}

struct CodegenArgs {
  std::string config_path;
  std::vector<std::string> targets;
  bool ignore_stamp = false;
};

}  // namespace

Result<std::string> DiscoverManifestInCwd() {
  std::error_code ec;
  fs::path cwd = fs::current_path(ec);
  if (ec) {
    return Err<std::string>(rex::ErrorCategory::IO,
                            fmt::format("Cannot read current directory: {}", ec.message()));
  }

  std::vector<fs::path> manifests;
  std::vector<fs::path> other_tomls;
  for (const auto& entry : fs::directory_iterator(cwd, ec)) {
    if (ec)
      break;
    if (!entry.is_regular_file())
      continue;
    if (entry.path().extension() != ".toml")
      continue;
    auto stem = entry.path().stem().string();
    if (stem.size() >= 9 && std::string_view{stem}.substr(stem.size() - 9) == "_manifest") {
      manifests.push_back(entry.path());
    } else {
      other_tomls.push_back(entry.path());
    }
  }

  if (manifests.size() == 1)
    return rex::Ok(manifests.front().string());
  if (manifests.size() > 1) {
    return Err<std::string>(
        rex::ErrorCategory::Config,
        fmt::format("Multiple *_manifest.toml files in {}; pass one explicitly", cwd.string()));
  }
  if (other_tomls.size() == 1)
    return rex::Ok(other_tomls.front().string());
  if (other_tomls.size() > 1) {
    return Err<std::string>(
        rex::ErrorCategory::Config,
        fmt::format("Multiple .toml files in {}; pass the manifest explicitly", cwd.string()));
  }
  return Err<std::string>(rex::ErrorCategory::Config,
                          fmt::format("No manifest .toml found in {}", cwd.string()));
}

Result<void> CodegenFromConfig(const std::string& config_path, const CliContext& ctx,
                               const std::vector<std::string>& targets, bool ignore_stamp) {
  REXLOG_TRACE("Generating code with config: {}", config_path);

  fs::path manifest_path = config_path;
  if (!rex::codegen::ManifestConfig::IsManifest(manifest_path)) {
    return Err<void>(
        rex::ErrorCategory::Config,
        fmt::format("{} is not a manifest: no [project] section. Pre-manifest single-file "
                    "configs are no longer converted automatically; see docs for the layout.",
                    config_path));
  }

  auto loaded = LoadManifestSummary(manifest_path);
  if (!loaded)
    return Err<void>(loaded.error());
  auto summary = std::move(*loaded);

  const std::string current_version = REXGLUE_VERSION_FLOOR;
  EmitProjectHeader(manifest_path, summary);

  if (RefreshGeneratedGlue(manifest_path.parent_path(), summary.project_name, current_version,
                           summary.entrypoint_out_dir)) {
    REXLOG_INFO("Regenerated generated/rexglue.cmake for SDK v{}", current_version);
  }

  if (auto run_result = RecompileProject(manifest_path, ctx, targets, ignore_stamp); !run_result) {
    return run_result;
  }

  if (!rex::codegen::ManifestConfig::WriteSdkVersionStamp(manifest_path, current_version)) {
    REXLOG_WARN("Failed to stamp manifest sdkVersion");
  }
  return rex::Ok();
}

void RegisterCodegen(CLI::App& parent, const CliContext& ctx, DeferredAction& pending) {
  auto args = std::make_shared<CodegenArgs>();
  auto* sub = parent.add_subcommand("codegen", "Analyze and generate C++ code")->fallthrough();
  sub->add_option("config", args->config_path,
                  "Path to manifest TOML (auto-discovered in cwd if omitted)")
      ->type_name("PATH");
  sub->add_option("--target", args->targets,
                  "DLL target to build (repeatable; entrypoint always included)")
      ->type_name("NAME")
      ->take_all();
  sub->add_flag("--ignore-stamp", args->ignore_stamp,
                "Regenerate even when inputs match the recorded stamp");

  sub->callback([args, &ctx, &pending]() {
    pending = [args, &ctx]() -> Result<void> {
      std::string path = args->config_path;
      if (path.empty()) {
        auto discovered = DiscoverManifestInCwd();
        if (!discovered)
          return Err<void>(discovered.error());
        path = *discovered;
      }
      return CodegenFromConfig(path, ctx, args->targets, args->ignore_stamp);
    };
  });
}

}  // namespace rexglue::cli
