name: Build rexglue-sdk mac-arm64

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  actions: write

jobs:
  build:
    uses: ./.github/workflows/_build-platform.yaml
    with:
      platform: mac-arm64
      ref: ${{ github.ref }}
      publish_mode: release
    secrets: inherit
